/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package textform;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author HP
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTextArea = new javax.swing.JTextArea();
        buttonProsesText = new javax.swing.JButton();
        buttonClearTextArea = new javax.swing.JButton();
        buttonSaveProsesText = new javax.swing.JButton();
        txtJumlahKarakterDiluarSpasi = new javax.swing.JTextField();
        txtJumlahBaris = new javax.swing.JTextField();
        txtJumlahHurufVokal = new javax.swing.JTextField();
        txtJumlahHurufKonsonan = new javax.swing.JTextField();
        labelJumlahKarakter = new javax.swing.JLabel();
        labelJumlahBaris = new javax.swing.JLabel();
        labelJumlahHurufVokal = new javax.swing.JLabel();
        labelJumlahHurufKonsonan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemOpen = new javax.swing.JMenuItem();
        menuItemSave = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTextArea.setColumns(20);
        txtTextArea.setRows(5);
        jScrollPane1.setViewportView(txtTextArea);

        buttonProsesText.setText("Proses Text");
        buttonProsesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesTextActionPerformed(evt);
            }
        });

        buttonClearTextArea.setText("Clear Text Area");
        buttonClearTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearTextAreaActionPerformed(evt);
            }
        });

        buttonSaveProsesText.setText("Save Proses Text (*.txt)");
        buttonSaveProsesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveProsesTextActionPerformed(evt);
            }
        });

        txtJumlahKarakterDiluarSpasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahKarakterDiluarSpasiActionPerformed(evt);
            }
        });

        txtJumlahBaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahBarisActionPerformed(evt);
            }
        });

        labelJumlahKarakter.setText("Jumlah Karakter (diluar spasi) :");

        labelJumlahBaris.setText("Jumlah Baris :");

        labelJumlahHurufVokal.setText("Jumlah Huruf Vokal :");

        labelJumlahHurufKonsonan.setText("Jumlah Huruf Konsonan :");

        jMenu1.setText("File");

        menuItemOpen.setText("Open (*.txt)");
        menuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOpenActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemOpen);

        menuItemSave.setText("Save (*.txt)");
        menuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSave);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonProsesText)
                        .addGap(18, 18, 18)
                        .addComponent(buttonClearTextArea))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelJumlahBaris, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelJumlahKarakter, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJumlahBaris, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(txtJumlahKarakterDiluarSpasi))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonSaveProsesText)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelJumlahHurufKonsonan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJumlahHurufKonsonan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelJumlahHurufVokal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtJumlahHurufVokal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonProsesText)
                    .addComponent(buttonClearTextArea)
                    .addComponent(buttonSaveProsesText))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJumlahKarakter)
                    .addComponent(labelJumlahHurufVokal)
                    .addComponent(txtJumlahKarakterDiluarSpasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlahHurufVokal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlahBaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJumlahBaris)
                    .addComponent(labelJumlahHurufKonsonan)
                    .addComponent(txtJumlahHurufKonsonan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlahBarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahBarisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahBarisActionPerformed

    private void menuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOpenActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text files", "txt");
        fileChooser.setFileFilter(filter);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try {
                //baca file dan memasukkannya ke text area
                BufferedReader reader = new BufferedReader(new FileReader(selectedFile));
                String line = reader.readLine();

                while (line != null) {
                    txtTextArea.append(line + "\n");
                    line = reader.readLine();
                }
                reader.close();
            } catch (Exception e) {
                System.out.println("Error reading file: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_menuItemOpenActionPerformed

    private void menuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveActionPerformed
        JFileChooser filechooser = new JFileChooser();
        filechooser.setDialogTitle("Save File (*.txt)");
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        filechooser.setAcceptAllFileFilterUsed(false);
        
        FileNameExtensionFilter fileNameFilter = new FileNameExtensionFilter("Text Files (*.txt)", ".txt");
        filechooser.addChoosableFileFilter(fileNameFilter);
        
        int returnValue = filechooser.showSaveDialog(this);
        
        if(returnValue == JFileChooser.APPROVE_OPTION)
        {
            File file = filechooser.getSelectedFile();
            
            try {
                FileWriter fw = new FileWriter(file + ".txt");
                fw.write(txtTextArea.getText());
                //jika file berhasil tersimpan 
                JOptionPane.showMessageDialog(this, "FIle Berhasil DIsimpan","Berhasil",JOptionPane.INFORMATION_MESSAGE);
                fw.close();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal Menyimpan File","Gagal",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_menuItemSaveActionPerformed

    private void buttonProsesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesTextActionPerformed
        String mainText = txtTextArea.getText();
        mainText = mainText.trim().replaceAll("\\s+", "");
        int banyakKarakter = mainText.length();
        int baris = txtTextArea.getLineCount();
        int hurufVokal = 0;
        int hurufKonsonan = 0;
        
        for (int i = 0; i < banyakKarakter; i++) {
            if (mainText.charAt(i) == 'a' || mainText.charAt(i) == 'A' || mainText.charAt(i) == 'i' || mainText.charAt(i) == 'I'
                    || mainText.charAt(i) == 'u' || mainText.charAt(i) == 'U' || mainText.charAt(i) == 'e' || mainText.charAt(i) == 'E'
                    || mainText.charAt(i) == 'o' || mainText.charAt(i) == 'O') {
                hurufVokal++;
            } else {
                hurufKonsonan++;
            }
        }
        
        if (txtJumlahKarakterDiluarSpasi.getText() != "") {
            txtJumlahKarakterDiluarSpasi.setText(Integer.toString(banyakKarakter));
        }

        if (banyakKarakter == 0) {
            txtJumlahBaris.setText(Integer.toString(0));
        } else {
            txtJumlahBaris.setText(Integer.toString(baris));
        }

        if (txtJumlahHurufVokal.getText() != "") {
            txtJumlahHurufVokal.setText(Integer.toString(hurufVokal));
        }

        if (txtJumlahHurufKonsonan.getText() != "") {
            txtJumlahHurufKonsonan.setText(Integer.toString(hurufKonsonan));
        }
    }//GEN-LAST:event_buttonProsesTextActionPerformed

    private void buttonClearTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearTextAreaActionPerformed
        txtTextArea.setText("");
        txtJumlahKarakterDiluarSpasi.setText("");
        txtJumlahBaris.setText("");
        txtJumlahHurufVokal.setText("");
        txtJumlahHurufKonsonan.setText("");
    }//GEN-LAST:event_buttonClearTextAreaActionPerformed

    private void buttonSaveProsesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveProsesTextActionPerformed
       JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save File (*.txt)");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);

        FileNameExtensionFilter fileNameFilter = new FileNameExtensionFilter("Text Files (*.txt)", "txt");
        fileChooser.addChoosableFileFilter(fileNameFilter);

        int returnValue = fileChooser.showSaveDialog(this);
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {

            File file = fileChooser.getSelectedFile();
            try {
                FileWriter fw = new FileWriter(file + ".txt");
                fw.write("\nJumlah karakter (diluar spasi): " + txtJumlahKarakterDiluarSpasi.getText() + "\n");
                fw.write("Jumlah baris : " + txtJumlahBaris.getText() + "\n");
                fw.write("Jumlah huruf vokal: " + txtJumlahHurufVokal.getText() + "\n");
                fw.write("Jumlah huruf Konsonan: " + txtJumlahHurufKonsonan.getText() + "\n");

                // pesan jika sukses
                JOptionPane.showMessageDialog(this, "File berhasil disimpan", "Success", JOptionPane.INFORMATION_MESSAGE);
                fw.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan file", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
               
       
    }//GEN-LAST:event_buttonSaveProsesTextActionPerformed

    private void txtJumlahKarakterDiluarSpasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahKarakterDiluarSpasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahKarakterDiluarSpasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClearTextArea;
    private javax.swing.JButton buttonProsesText;
    private javax.swing.JButton buttonSaveProsesText;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelJumlahBaris;
    private javax.swing.JLabel labelJumlahHurufKonsonan;
    private javax.swing.JLabel labelJumlahHurufVokal;
    private javax.swing.JLabel labelJumlahKarakter;
    private javax.swing.JMenuItem menuItemOpen;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JTextField txtJumlahBaris;
    private javax.swing.JTextField txtJumlahHurufKonsonan;
    private javax.swing.JTextField txtJumlahHurufVokal;
    private javax.swing.JTextField txtJumlahKarakterDiluarSpasi;
    private javax.swing.JTextArea txtTextArea;
    // End of variables declaration//GEN-END:variables
}
